services:
  #development service
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - "5000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev

    #production service
  app-prod:
    container_name: nestjs-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    depends_on:
      - db
    ports: 
      - "8080:3000"
    profiles:
      - prod
      

  #Database service [postgresql]
  db:
    image: postgres:16-alpine
    container_name: nestjs-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  #pgAdmin service [postgresql]
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nestjs-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: